#!/usr/bin/python

import sys

def parse(filename):
    return [line.strip().split() for line in open(filename,  "rb").readlines()]

data1 = parse(sys.argv[1])
data2 = parse(sys.argv[2])

data = zip(data1, data2)
data = [list(set(d1).intersection(d2)) for (d1, d2) in data]
for d in data:
    print " ".join(d)
