#!/usr/bin/python

import sys

def reverse(txt):
    return "".join(list(txt)[::-1])

data = [line.strip().split() for line in sys.stdin.readlines()]
for aligns in data:
    for align in aligns:
        src, tgt = align.split("-")
        print tgt+"-"+src,
    print ""
